### PR TITLE
Templatehelper

### PR DESCRIPTION
**Pull request by chregu**
Some general documentation about this is here for now: https://github.com/rokka-io/rokka-site/blob/php-intro/source/_guides/6-php-client-intro.md

### CODE REVIEW

**Review by michellesanver — APPROVED** [review]

**Comment by thePanz** [comment]
@michellesanver @chregu Shouldn't the class `LocalImageAbstract` have the `Abstract` as prefix instead of as suffix (thus: `AbstractLocalmage`?)

**Comment by chregu** [comment]
mmmh, so Abstract is in the beginning and Interface in the end? Is that how it's done?

**Comment by thePanz** [comment]
@chregu maybe I am getting confused, as we never picked a "naming convention" for this library.
btw: I was referring to https://symfony.com/doc/current/contributing/code/standards.html#naming-conventions :)

**Comment by chregu** [comment]
ok, renamed it and also StackAbstract to AbstractStack
and put the templaterhelper "sub" classes into their own namespace `Rokka\Client\TemplateHelper`

**Pull request merged**
